[package]
name = "rust-url-shortener"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
harsh = { version = "*" }
rand = { version = "*" }
actix-web = { version = "*" }
serde = { version = "*", features = ["derive"] }
sqlx = { version = "0.6", features = ["runtime-tokio-rustls", "postgres"] }
